{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "lfgw-operator-chart.serviceAccountName" . }}-acl-crud
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "lfgw-operator-chart.fullname" . }}-acl-crud
subjects:
- kind: ServiceAccount
  name: {{ include "lfgw-operator-chart.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "lfgw-operator-chart.serviceAccountName" . }}-configmap-crud
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "lfgw-operator-chart.fullname" . }}-configmap-crud
subjects:
- kind: ServiceAccount
  name: {{ include "lfgw-operator-chart.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
