apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lfgw.fullname" . }}
  labels:
    {{- include "lfgw.labels" . | nindent 4 }}
  annotations: {{ .Values.annotations | toYaml | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "lfgw.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }} 
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}     
        {{- end }}  
      labels:
        {{- include "lfgw.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "lfgw.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if  or .Values.envs }}
          envFrom:
            - configMapRef:
                name: {{ include "lfgw.fullname" . }}-env
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: acl-volume
            {{- if index .Values "extraConfigMap" "enabled" }}
            mountPath: {{ .Values.extraConfigMap.mountPath }}
            {{- else }}
            mountPath: {{ .Values.aclConfigMap.mountPath }}
            {{- end }}
            readOnly: true
      volumes:
      - name: acl-volume
        configMap:
          {{- if index .Values "lfgw-operator-chart" "enabled" }}
          name: {{ index .Values "lfgw-operator-chart" "envs" "CM_NAME"}}
          {{- else if index .Values "extraConfigMap" "enabled" }}
          name: {{ .Values.extraConfigMap.name }}
          {{- else }}
          name: {{ include "lfgw.fullname" . }}          
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
